Feature/skip to link
whitespace-se/components pull request #6
Opened 2021-10-04 10:01 UTC by Okkido

2021-10-06 16:44 UTC, jeanfredrik requested changes

2021-10-06 16:44 UTC, jeanfredrik commented on pkg/src/components/FormFieldDescription.module.css
> +  padding-bottom: var(--form-description-padding-bottom);
Do we need these?

2021-10-06 16:44 UTC, jeanfredrik commented on pkg/src/components/FormRadioGroupField.module.css
> +  border: #5046e4;
These should be set via custom props

2021-10-06 16:44 UTC, jeanfredrik commented on pkg/src/components/FormRadioGroupField.module.css
> +  background: #fff;
This should be set via custom props

2021-10-07 15:37 UTC, Okkido commented on pkg/src/components/FormCheckboxField.js
> +                    indeterminate="indeterminate"
Correct. I started adding support for a indeterminate state but removed the style since out was out of scope but forgot to remove the attribute.

2021-10-08 07:53 UTC, Okkido commented on pkg/src/components/FormFieldDescription.module.css
> +  padding-bottom: var(--form-description-padding-bottom);
Nope!

2021-10-08 10:54 UTC, jeanfredrik approved these changes

2021-10-08 10:54 UTC, merged